---
title: "Handout"
author: "Tabitha K. Peter"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Collaborative health science research begins with a research question

## Menu overview: what are the steps in conducting dental research?

1.  Write down a research question that articulates what you want to learn
2.  Identify what type of study you need to answer your question
3.  Determine the type(s) of data you need to collect
4.  Choose an appropriate study design

# Identifying the type of study

## Observational v. experimental

-   **Observational** studies collect data from an existing system without intentionally interfering with that system

-   **Experimental** studies involve the investigator(s) deliberately setting one or more factors in a system to a specific level

# Determining the type of data

## Independent v. correlated 

- **Independent** data consist of observational units whose outcomes do not mutually affect the probability of one another. 

- **Correlated** data consist of observational units wherein the probability of the outcome is impacted by some kind of relational structure. Examples: teeth in the same mouth, people in the same family, repeated measurements from the same subject.  

# Choosing a study design

## Data type is usually determined by the outcome 

Consider your research question: 

  - which element is the outcome (dependent variable)? 
  - which element is the explanatory (independent) variable of greatest interest? 
  - are there any factor(s) for which you want to control? 

## How long until (some event of interest) happens?

-   Addressing this kind of question requires **time-to-event (survival)** data
-   Outcome: time until the event happens
-   Dates are the key data to collect for this outcome

### Examples of time-to-event research questions

-   How long do crown margin repairs usually last for patients treated at CoD?
-   How long until dentures need to be refitted?

## What happens to (some unit of study) over time?

-  Addressing this kind of question requires **longitudinal** data. 
-  This kind of data involves repeatedly measuring the study units at several points in time.

### Examples of longitudinal research questions

-   How does fluoride exposure impact dental caries over the course of childhood?
-   Is nonsurgical periodontal treatment associated with improved kidney function over time?

## Are the (units of study) in group A different than those in group B?

-   This kind of study is typically a **case-control** study, where the two groups you want to compare are the "case" group and the "control" group. 

### Examples of case-control research questions

-   Do mice born with nonsyndromic orofacial clefts have more (or fewer) dental anomalies compared to mice with no orofacial birth defects?

-   How (if at all) does the oral microbiome of patient with oral cancer differ from the oral microbiome of a patient with no oral disease?

## What do people in this specific group think/experience/learn/have access to?

-   Addressing this type of question often calls for a **survey.** 
-   Survey studies are most commonly **observational**

### Examples of survey research questions

-   Do patients living in skilled nursing facilities who demonstrate evidence of a cognitive impairment face increased challenges in maintaining oral hygiene practices?

-   Are patients who demonstrate a basic knowledge of their periodontal healthcare needs more satisfied with their treatment compared to patients who do not demonstrate such knowledge?

## What generalization can we make about the literature in this specific area?

-   A study that studies other studies is a **meta-analysis**. Specifically, the aim of a meta-analysis is to aggregate results from the literature in a particular field and make a generalization.

-   As more journals are requiring investigators to publish their data along with their results, aggregating data sets across multiple studies and analyzing this mega data is becoming a more popular approach. This is called **mega-analysis**.

### Examples of meta-analysis research questions

-   Surveying the literature on the oral microbiome in patients diagnosed with COVID-19, what generalization can we make about the patterns of dysbiosis observed in such patients?

-   Does the dental materials literature demonstrate a consensus regarding the impact of resin-modified glass ionomer (GI), instead of regular GI? 
